name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Clutter
      run: sudo apt-get update && sudo apt-get install libclutter-1.0-dev libpango1.0-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  clippy_check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - name: Install Clutter
        run: sudo apt-get update && sudo apt-get install libclutter-1.0-dev libpango1.0-dev
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
